blogger/config/routes.rb
Blogger::Application.routes.draw do
  resources :comments

  devise_for :users
  root 'users#index'
  resources :users
  resources :posts

end

blogger/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

blogger/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user

end

blogger/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user #:category
	has_many :comments

	# attr_accessible :title, :description, :image, :user_id
end

blogger/app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts #:comments
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 


end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

blogger/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all

  end

  def new
  	@post = Post.new
  end

  def show
  	@post = Post.find(params[:id])
  end

  def create
  	@post_params = params.require(:post).permit(:title, :description, :image, :user_id)
  	@post = Post.new(@post_params)
  	if @post.save 
  			redirect_to @post, :notice => "Your post entry is successfully saved!"
  	else
  		render action: 'new'
  	end
  end

  def update
  end

  def delete
  end
end

blogger/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new  
  end

  def show
  end

  def update
  end

  def delete
  end
end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/comments_helper.rb
module CommentsHelper
end

blogger/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blogger/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

blogger/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Post</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

blogger/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

blogger/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>




<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

blogger/app/views/posts/_form.html.erb
<%= form_for (@post) do |f| %>

<% if @post.errors.any? %>
  <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:<br>
  <% @post.errors.full_messages.each do |msg| %>
    <%= msg %><br>
  <% end %>
<% end %>

    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
    <%= f.label :image %>
    <%= f.text_field :image %><br>
    <%= f.hidden_field :user_id, :value => current_user.id%>
    <%= f.submit %>

<% end %>

blogger/app/views/posts/_listing_post.html.erb
<% @posts.each do |post| %>

<h3><%= post.title %></h3><br>
<%=post.description%><br>
<img src="/images/<%= post.image %>" /><br>

<%= link_to 'Show', post %>
<%= link_to 'Edit', edit_post_path(post) %>
<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you absolutely sure?'} %>
		  
<hr>

<% end %>

blogger/app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

blogger/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Post</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.description %></td>
        <td><%= post.user_id %></td>
        <td><%= post.post_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New post', new_post_path %>

blogger/app/views/posts/new.html.erb
<%= render "form" %>

blogger/app/views/posts/show.html.erb
<h1>Showing your post <%= params[:id] %></h1>

<strong>Title:</strong> <%= @post.title %> <br>
<strong>Description:</strong> <%= @post.description %> <br>
<strong>Image:</strong> <%= @post.image %> <br>
<strong>Display:</strong> <%= @post.user.email %> <br>
<p2><%= link_to 'Back', posts_path %></p2>

blogger/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

blogger/app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

blogger/app/views/users/index.html.erb
<h1>Welcome to Blogger</h1>
<p></p>

blogger/app/views/users/new.html.erb
<%= render "form" %>

blogger/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

blogger/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>